mod app;
mod client;

use app::erro::Error;

#[tokio::main]
async fn main() -> Result<(), Error> {
    
    Ok(())
}